### ISSUE TITLE
::1 notation being removed

### ISSUE THREAD

**Issue by amatiash** [TheBrenny/hosts-etc-cli#1]
Why does `::1 localhost` notation being removed from `/etc/hosts`?

I use macOS 10.14.6. Command: `sudo hosts -r "myhost.com"`

**Comment by TheBrenny** [comment]
I'd say it's because when `hosts-etc` [reads the hostfile first](https://github.com/TheBrenny/hosts-etc/blob/8ec15c4616ea2460ef2b5928b65b57594c908987/hosts-etc.js#L103), but since `::1 localhost` doesn't match the regex on [this line](https://github.com/TheBrenny/hosts-etc/blob/8ec15c4616ea2460ef2b5928b65b57594c908987/hosts-etc.js#L108), it's not getting picked up.

This was an oversight on my part, because [Windows handles this](https://serverfault.com/a/803078).

I'm going to open an issue at [TheBrenny/hosts-etc](https://github.com/TheBrenny/hosts-etc) because the problem is actually there.

Thanks for catching this one though! 🎉
